### ISSUE TITLE
Error on initial install.

### ISSUE THREAD

**Issue by adamlauretig** [jason-morgan/dynnet#4]
This threw an error initially `ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran`, which this post: http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/ helped me solve.

Not sure if there's a general solution, but just a heads up.

**Comment by jason-morgan** [comment]
Thank you. I will have to check what the requirements for compilation are on Mac and whether that is something the package needs to deal with.

**Comment by adamlauretig** [comment]
No problem.  Based on that message, it seems like:

(pseudocode)
if  (gfortran version < 4.8.2) { throw errormessage}
else {install(dynnet)}

before installation might work, especially since its a more general Rcpp problem.

**Comment by jason-morgan** [comment]
I am going to close this issue, since it is a general RcppArmadillo problem on Mac, not an issue with dynnet per se. But I have linked to this thread in the installation section of the README.
